# Site settings
author: Travis T
title: Travis.Learn
header-img: img/home-bg.png
email: travistokuyama@gmail.com
copyright_name: Travis T
description: > # this means to ignore newlines until "baseurl:"
  Learning to learn
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  trav15

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
